version: 2

jobs:
  build:
    docker:
    - image: circleci/clojure:lein-2.7.1
    # @see https://discuss.circleci.com/t/how-to-disable-mysql-strict-mode-in-circleci-2/13503
    - image: mysql:5.7.16
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: ''
      command:
        mysqld --sql-mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    working_directory:    ~/press-review-clojure

    environment:
      LEIN_ROOT:          "true"
      JVM_OPTS:           -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install MySQL client
          command: |
            sudo apt update && sudo apt install -y mysql-client

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies

      - run:
          name: Copy test configuration
          command: |
            cp .lein-env.test.dist .lein-env

      - run:
          name: Wait for the database to be up and ready
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: Create database
          command: |
            mysql -uroot -h127.0.0.1 test < ~/press-review-clojure/build/schema.sql

      - run:
          name: Install dependencies
          command: |
            lein deps

      - run:
          name: Run test suite
          command: |
            lein test

      - save_cache:
          key: v1-dependencies-{{ checksum "project.clj" }}
          paths:
          - $HOME/.m2
          - $HOME/.lein
